"""
metrics.py
==========
Performance and risk metrics for evaluating portfolios, applied to the
realized (in-sample, historical) monthly return series generated by a
given weight vector.

All formulas are documented inline. Inputs are monthly return series in
DECIMAL form (e.g. 0.012 = +1.2%) unless stated otherwise.
"""

from __future__ import annotations

import numpy as np
import pandas as pd


def portfolio_monthly_returns(returns_df: pd.DataFrame, weights: pd.Series) -> pd.Series:
    """
    Realized monthly portfolio return time series:

        R_p,t = sum_i  w_i * R_i,t

    i.e. the fixed-weight (buy-and-hold-then-rebalance-every-period)
    portfolio return in each historical month. `returns_df` is expected in
    PERCENT (as loaded from Ken French); we convert to decimal internally.
    """
    w = weights.reindex(returns_df.columns).fillna(0.0)
    return (returns_df / 100.0) @ w


def annualized_return(monthly_returns: pd.Series) -> float:
    """
    Compound Annual Growth Rate (CAGR) computed from a monthly return
    series:

        R_annual = (prod_t (1 + R_t))^(12/T) - 1

    This correctly accounts for compounding, unlike simply multiplying the
    arithmetic mean monthly return by 12.
    """
    cumulative_growth = (1 + monthly_returns).prod()
    n_months = len(monthly_returns)
    return cumulative_growth ** (12 / n_months) - 1


def annualized_volatility(monthly_returns: pd.Series) -> float:
    """
    Annualized volatility (standard deviation), scaling the monthly sample
    standard deviation by sqrt(12) under the i.i.d.-returns assumption:

        sigma_annual = sigma_monthly * sqrt(12)
    """
    return monthly_returns.std(ddof=1) * np.sqrt(12)


def sharpe_ratio(monthly_returns: pd.Series, risk_free_rate_annual: float = 0.0) -> float:
    """
    Annualized Sharpe Ratio (Sharpe, 1966):

        Sharpe = (R_annual - R_f) / sigma_annual

    Measures excess return earned per unit of total risk (volatility).
    Here R_f is the ANNUAL risk-free rate (default 0 for simplicity /
    since the French library also publishes a risk-free series that can be
    substituted in).
    """
    r_annual = annualized_return(monthly_returns)
    vol_annual = annualized_volatility(monthly_returns)
    if vol_annual == 0:
        return np.nan
    return (r_annual - risk_free_rate_annual) / vol_annual


def max_drawdown(monthly_returns: pd.Series) -> float:
    """
    Maximum Drawdown (MDD): the largest peak-to-trough decline in the
    cumulative wealth curve, expressed as a negative percentage.

        Wealth_t = prod_{s<=t} (1 + R_s)
        Drawdown_t = Wealth_t / running_max(Wealth_{<=t}) - 1
        MDD = min_t Drawdown_t

    A key downside-risk metric that Sharpe ratio alone does not capture --
    critical for evaluating tail risk, which quant funds (and interviewers)
    care about deeply.
    """
    wealth_index = (1 + monthly_returns).cumprod()
    running_max = wealth_index.cummax()
    drawdown = wealth_index / running_max - 1.0
    return drawdown.min()


def cumulative_returns(monthly_returns: pd.Series) -> pd.Series:
    """Cumulative wealth curve, normalized to start at 1.0 (i.e. 100%)."""
    return (1 + monthly_returns).cumprod()


def rolling_volatility(monthly_returns: pd.Series, window: int = 12) -> pd.Series:
    """
    Rolling annualized volatility over a trailing `window`-month window.
    Useful for visualizing time-varying risk (regime shifts, crises, etc.).

        sigma_roll,t = std(R_{t-window+1 : t}) * sqrt(12)
    """
    return monthly_returns.rolling(window).std(ddof=1) * np.sqrt(12)


def correlation_matrix(returns_df: pd.DataFrame) -> pd.DataFrame:
    """
    Pearson correlation matrix of the individual asset (industry) returns:

        rho_{ij} = Cov(R_i, R_j) / (sigma_i * sigma_j)

    Correlation (unlike covariance) is scale-free and directly shows
    diversification potential -- low/negative off-diagonal entries are what
    the GMV optimizer exploits to reduce portfolio variance below any
    single asset's variance.
    """
    return returns_df.corr()


def summary_table(
    returns_df: pd.DataFrame,
    weights_dict: dict[str, pd.Series],
    risk_free_rate_annual: float = 0.0,
) -> pd.DataFrame:
    """
    Build a side-by-side comparison table of all key metrics for multiple
    portfolios (e.g. {'GMV': gmv_weights, 'Equal Weight': ew_weights, ...}).
    """
    rows = []
    for name, w in weights_dict.items():
        port_ret = portfolio_monthly_returns(returns_df, w)
        rows.append({
            "Portfolio": name,
            "Annualized Return": annualized_return(port_ret),
            "Annualized Volatility": annualized_volatility(port_ret),
            "Sharpe Ratio": sharpe_ratio(port_ret, risk_free_rate_annual),
            "Max Drawdown": max_drawdown(port_ret),
            "Effective N (1/HHI)": 1.0 / np.sum(w.values ** 2),
        })
    return pd.DataFrame(rows).set_index("Portfolio")
